#
# File: drivers/net/aud_lan/Makefile
#
# Siemens Industry Sector IA ATS 11 h.b.
# 14-August-2008
# overtaken for kernel 2.6.31.12 by m.n.
#

obj-$(CONFIG_MIPS_ETHER_SOC)			+= soc_lan.o
obj-$(CONFIG_MIPS_ETHY_SOC)			+= ethy/
