#ifndef __ASM_GENERIC_SETUP_H
#define __ASM_GENERIC_SETUP_H

#ifdef CONFIG_AUD_EXTEND_COMMAND_LINE
#define COMMAND_LINE_SIZE	CONFIG_AUD_EXTEND_COMMAND_LINE
#else
#define COMMAND_LINE_SIZE	512
#endif

#endif	/* __ASM_GENERIC_SETUP_H */
