#
# Makefile for the AuD application device driver
#



obj-$(CONFIG_AUD_PBUS_PLUS) += pbus_plus.o
 
obj-$(CONFIG_AUD_KERNEX) += kernex_default.o

obj-$(CONFIG_AUD_BOARDEX) += boardex_default.o

obj-$(CONFIG_AUD_CPXXX5HW) += cpXXX5hw_default.o

obj-$(CONFIG_AUD_RUNFW) += runfw_default.o

obj-$(CONFIG_AUD_SIMPLE_SYNC_TIMER) += simple_sync_timer_driver.o

obj-$(CONFIG_AUD_SIMPLE_EVENT_DRIVER) += simple_event_driver.o

obj-y += powerpc/
